version: 2
updates:
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: "daily"
    assignees:
      - "ryohidaka"
    labels:
      - "dependencies"
      - "automerge"
    open-pull-requests-limit: 20
